<?php

/**
 * @file
 * Primary module hooks for Bundle Classes Demo module.
 */

use Drupal\bundle_classes_demo\Entity\Node\Article;
use Drupal\bundle_classes_demo\Entity\Node\Page;
use Drupal\bundle_classes_demo\Entity\Node\LandingPage;
use Drupal\bundle_classes_demo\Entity\Paragraphs\RichText;
use Drupal\bundle_classes_demo\Entity\Media\Image;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function bundle_classes_demo_entity_bundle_info_alter(&$bundles): void {
  $entity_type_bundle_classes = [
    'node' => [
      Article::BUNDLE => Article::class,
      Page::BUNDLE => Page::class,
      LandingPage::BUNDLE => LandingPage::class,
    ],
    'paragraph' => [
      RichText::BUNDLE => RichText::class,
    ],
    'media' => [
      Image::BUNDLE => Image::class,
    ]
  ];
  foreach ($entity_type_bundle_classes as $entity_type => $bundle_classes) {
    foreach ($bundle_classes as $bundle => $class) {
      if (isset($bundles[$entity_type][$bundle])) {
        $bundles[$entity_type][$bundle]['class'] = $class;
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function bundle_classes_demo_theme($existing, $type, $theme, $path): array {
  return [
    'landing_page_header' => [
      'variables' => [
        'title' => '',
        'image' => '',
        'summary' => '',
      ],
    ],
  ];
}
